name: Build

# Run the build on every push and pull request.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PATH: ~/.local/bin:$PATH
    steps:
    # Echo-debug the PATH.
    - name: Where is PATH-me? Is she safe? Is she...alright?
      run: echo $PATH

    # Checkout the repository under $GITHUB_WORKSPACE.
    - uses: actions/checkout@v2

    # Install the necessary tools and dependencies for the build. Note that
    # pip installs meson/ninja for the current user only, meaning they end
    # up in ~/.local/bin, which is not on the $PATH.
    - name: Run ./configure
      run: ./configure

    # Generate the ninja build files with meson.
    - name: Generate build
      run: meson setup build

    # Actually perform the build.
    - name: Run the build
      run: cd build/ && ninja

    # Run the unit tests.
    - name: Run tests
      run: cd build/ && meson test
