name: Build

# Run the build on every push and pull request, regardless of branch.
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository under $GITHUB_WORKSPACE.
    - uses: actions/checkout@v2

    # Update Python to a fixed version to avoid changes with Python/pip breaking
    # the build.
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Install Graphviz and Doxygen for the documentation targets.
    - name: Install Graphviz, Doxygen
      run: sudo apt -y install doxygen graphviz
  
    # To make sure the following steps can use meson/ninja, prepend their 
    # install path to the current path using the "add-path" workflow command.
    # See: https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
    - name: Put /home/runner/.local/bin on PATH
      run: echo "::add-path::/home/runner/.local/bin"

    # Install the necessary tools and dependencies for the build. Note that
    # pip installs meson/ninja for the current user only, meaning they end
    # up in ~/.local/bin, which is not on the $PATH.
    - name: Run ./configure
      run: ./configure

    # Generate the ninja build files with meson.
    - name: Generate build
      run: meson setup build

    # Actually perform the build.
    - name: Run the build
      run: cd build/ && ninja
      
    # Generate the doxygen documentation.
    - name: Generate docs
      run: cd build/ && ninja docs

    # Run the unit tests.
    - name: Run tests
      run: cd build/ && meson test
